<?php
include_once 'utils.php';
include_once 'dictionary.php';

$chippedBlocks1 = [
  'botanist\'s workbench' => 'botanikus munkapad',
  'carpenter\'s workbench' => 'asztalosműhely',
  'glassblower\'s workbench' => 'üvegfújó munkapad',
  'shepherd\'s workbench' => 'szővőszék',
  'mason\'s workbench' => 'kőműves munkapad',
  'fine mosaic' => 'finom mozaik',
];

$chippedBlocks2 = [
  'alchemy bench' => 'alkímia munkapad',
  'carpenters table' => 'asztalosműhely',
  'botanist workbench' => 'botanikus munkapad',
  'glassblower' => 'úvegfújó',
  'loom table' => 'szövőszék',
  'mason table' => 'kőműves asztal',
  'tinkering table' => 'kontárasztal',
  'workbench' => 'munkapad',
  'multimeter' => 'multiméter',
  'saw' => 'fűrész',
  'watering can' => 'öntözőkanna',
  'scales' => 'pikkelyek',
  'shavings' => 'forgácsok',
  'mosaic' => 'mozaik',
  'brick bordered' => 'téglás keretes',
  'brick bond' => 'téglás',
  'basket woven' => 'kosárfonott',
  'vertical cut' => 'függőleges vágott',
  'horizontal cut' => 'vízszintes vágott',
  'panels' => 'panelek',
  'double herringbone' => 'dupla halszálkás',
  'dual paneled' => 'dupla panelezett',
  'center cut' => 'középen vágott',
  'edge cut' => 'szélén vágott',
  'half grown' => 'félig nőtt',
];

$chippedModifiers = [

  'airy' => 'levegős',
  'angry' => 'dühös',
  'angled' => 'szögletes',
  'apple' => 'almás',
  'arched' => 'íves',
  'arch' => 'ív',
  'antique' => 'antik',
  'anguished' => 'gyötrődő', // kínlódó?
  'bad time' => 'rossz idő',
  'barbed' => 'tüskés',
  'barky' => 'kérges',
  'barred' => 'rácsos',
  'basket' => 'kosaras',
  'beach' => 'parti',
  'big' => 'nagy',
  'blank' => 'üres',
  'blobby' => 'pöppeteg',
  'blocky' => 'tömbös',
  'bloom' => 'virág',
  'blooming' => 'virágzó',
  'bloomed' => 'virágzott',
  'boarded' => 'deszkás',
  'bolted' => 'csavart',
  'bordered' => 'keretes',
  'borderless' => 'keret nélküli',
  'botanical' => 'botanikai',
  'bubbling' => 'buborékos',
  'boxed' => 'dobozos',
  'bricky' => 'téglás',
  'bright' => 'fényes',
  'broken' => 'törött',
  'bulby' => 'gumós',
  'bulbed' => 'gumós',
  'bundled' => 'kötözött',
  'bushy' => 'bokros',
  'button' => 'gombos',
  'carved' => 'faragott',
  'carving' => 'faragás',
  'centered' => 'középre igazított',
  'chained' => 'láncos',
  'checkered' => 'kockás',
  'chipped' => 'csorba',
  'chiseled' => 'vésett',
  'chunky' => 'darabos',
  'circled' => 'kör alakú',
  'circular' => 'kör alakú',
  'classic' => 'klasszikus',
  'clear' => 'átlátszó',
  'clustered' => 'csokros',
  'coarse' => 'terméketlen',
  'cobbled' => 'kövezett',
  'cornered' => 'sarkos',
  'corny' => 'kukoricás',
  'corrupted' => 'romlott',
  'compact' => 'tömör',
  'cracked' => 'repedezett',
  'crafted' => 'fortélyos',
  'crated' => 'dobozos',
  'creepy' => 'ijesztő',
  'creeping' => 'kúszó',
  'crooked' => 'görbe',
  'cross haired' => 'keresztszemes',
  'cross laced' => 'keresztszemes',
  'crossbolted' => 'keresztszemes',
  'crossed' => 'keresztezett',
  'crumbled' => 'morzsolt',
  'crunched' => 'összenyomott',
  'crunchy' => 'ropogós',
  'crusted' => 'kérgezett',
  'crying' => 'könnyező',
  'cubed' => 'kockás',
  'curled' => 'göndör',
  'curly' => 'göndör',
  'curvy' => 'görbült',
  'cut' => 'vágott',
  'damaged' => 'sérült',
  'dark' => 'sötét',
  'dotted' => 'pöttyös',
  'dusted' => 'porzó',
  'dusty' => 'poros',
  'disordered' => 'zavaros',
  'dead' => 'halott',
  'decorated' => 'díszített',
  'dense' => 'sűrű',
  'deailed' => 'részletes',
  'desert' => 'sivatagi',
  'devious' => 'ravasz',
  'diagonal' => 'átlós',
  'dirty' => 'földes',
  'distorted' => 'torzított',
  'donut' => 'fánk',
  'dot' => 'pötty',
  'double' => 'dupla',
  'droopy' => 'lógó',
  'duh' => 'botor',
  'edged' => 'éles',
  'elemental' => 'elemi',
  'embossed' => 'dombornyomott',
  'enclosed' => 'zárt',
  'engraved' => 'gravírozott',
  'eroded' => 'erodált',
  'erratic' => 'szabálytalan',
  'etched' => 'karcolt',
  'eye' => 'szemes',
  'eyed' => 'szemes',
  'faded' => 'halvány',
  'fancy' => 'divatos',
  'fertile' => 'termékeny',
  'fine' => 'finom',
  'fired' => 'égetett',
  'firewood' => 'tűzifa',
  'fish' => 'halas',
  'flower' => 'virágos',
  'flowering' => 'virágzó',
  'flowered' => 'virágozott',
  'flowery' => 'virágos',
  'flat' => 'lapos',
  'flimsy' => 'gyenge',
  'floral' => 'virágos',
  'fortified' => 'megerősített',
  'fractured' => 'repedezett',
  'framed' => 'keretes',
  'freckled' => 'szeplős',
  'frosted' => 'fagyos',
  'fruit' => 'gyümölcsös',
  'gated' => 'kapus',
  'giant' => 'óriás',
  'gilded' => 'aranyozott',
  'glad' => 'boldog',
  'glittering' => 'csillogó',
  'glow' => 'ragyogó',
  'glowing' => 'ragyogó',
  'golden' => 'arany',
  'graveled' => 'kavicsos',
  'grid' => 'rácsos',
  'grill' => 'rácsos',
  'grimy' => 'koszos',
  'hanging' => 'függő',
  'happy' => 'boldog',
  'hard' => 'kemény',
  'hardened' => 'megkeményedett',
  'harp' => 'hárfás',
  'harsh' => 'kemény',
  'inlayed' => 'berakott',
  'packed' => 'tömörített',
  'large' => 'nagy',
  'leaf' => 'leveles',
  'leafy' => 'leveles',
  'micro' => 'mikro',
  'paddle' => 'lapátos',
  'rough' => 'durva',
  'roped' => 'kötözött',
  'sides' => 'oldalak',
  'scaled' => 'pikkelyes',
  'spotted' => 'foltos',
  'sprinkled' => 'szórt',
  'smooth' => 'sima',
  'sign' => 'jelű',
  'top' => 'teteje',
];

// 2667

$data = processFile(
  '../originals/chipped/en_us.json',
  [
    ...$dictionary,
    $chippedBlocks1,
    $chippedBlocks2,
    $chippedModifiers,
  ]
);

// print_r($data);
saveAs($data, 'chipped.json');
